# Convolutional Neural Network

In [1]:
import numpy
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras import backend as K
K.set_image_dim_ordering('th')

Using TensorFlow backend.


In [2]:
# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)
# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
#For training images of 28X28
X_train.shape

(60000, 28, 28)

In [8]:
#For training labels
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
#For testing image of 28X28
X_test.shape

(10000, 28, 28)

In [9]:
#For testing labels
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [3]:
# reshape to be [samples][pixels][width][height]
X_train = X_train.reshape(X_train.shape[0], 1, 28, 28).astype('float32')
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28).astype('float32')

In [4]:
X_train

array([[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]]],


       ..., 
       [[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [

In [5]:
# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255

In [6]:
# one hot encode outputs
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]

In [7]:
# define the larger model
def larger_model():
    
    model = Sequential()
    model.add(Conv2D(30, (5, 5), input_shape=(1, 28, 28), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Conv2D(15, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [8]:
# build the model
model = larger_model()

In [9]:
# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 182s - loss: 0.3908 - acc: 0.8801 - val_loss: 0.0957 - val_acc: 0.9693
Epoch 2/10
60000/60000 [==============================] - 189s - loss: 0.0950 - acc: 0.9708 - val_loss: 0.0591 - val_acc: 0.9803
Epoch 3/10
60000/60000 [==============================] - 205s - loss: 0.0692 - acc: 0.9788 - val_loss: 0.0385 - val_acc: 0.9882
Epoch 4/10
60000/60000 [==============================] - 187s - loss: 0.0564 - acc: 0.9830 - val_loss: 0.0336 - val_acc: 0.9883
Epoch 5/10
60000/60000 [==============================] - 179s - loss: 0.0479 - acc: 0.9854 - val_loss: 0.0299 - val_acc: 0.9907
Epoch 6/10
60000/60000 [==============================] - 178s - loss: 0.0429 - acc: 0.9865 - val_loss: 0.0290 - val_acc: 0.9903
Epoch 7/10
60000/60000 [==============================] - 193s - loss: 0.0381 - acc: 0.9879 - val_loss: 0.0268 - val_acc: 0.9908
Epoch 8/10
60000/60000 [=======================

In [11]:

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Large CNN Error: %.2f%%" % (100-scores[1]*100))

Large CNN Error: 0.71%
